# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_pb2 as grpc__pb2


class Lab6GrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformAdd = channel.unary_unary(
                '/lab6.Lab6Grpc/PerformAdd',
                request_serializer=grpc__pb2.addMsg.SerializeToString,
                response_deserializer=grpc__pb2.addReply.FromString,
                )
        self.ImageDimensions = channel.unary_unary(
                '/lab6.Lab6Grpc/ImageDimensions',
                request_serializer=grpc__pb2.rawImageMsg.SerializeToString,
                response_deserializer=grpc__pb2.imageReply.FromString,
                )
        self.PerformDotProduct = channel.unary_unary(
                '/lab6.Lab6Grpc/PerformDotProduct',
                request_serializer=grpc__pb2.dotProductMsg.SerializeToString,
                response_deserializer=grpc__pb2.dotProductReply.FromString,
                )
        self.JsonImageDimensions = channel.unary_unary(
                '/lab6.Lab6Grpc/JsonImageDimensions',
                request_serializer=grpc__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=grpc__pb2.imageReply.FromString,
                )


class Lab6GrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageDimensions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformDotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JsonImageDimensions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Lab6GrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformAdd,
                    request_deserializer=grpc__pb2.addMsg.FromString,
                    response_serializer=grpc__pb2.addReply.SerializeToString,
            ),
            'ImageDimensions': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageDimensions,
                    request_deserializer=grpc__pb2.rawImageMsg.FromString,
                    response_serializer=grpc__pb2.imageReply.SerializeToString,
            ),
            'PerformDotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformDotProduct,
                    request_deserializer=grpc__pb2.dotProductMsg.FromString,
                    response_serializer=grpc__pb2.dotProductReply.SerializeToString,
            ),
            'JsonImageDimensions': grpc.unary_unary_rpc_method_handler(
                    servicer.JsonImageDimensions,
                    request_deserializer=grpc__pb2.jsonImageMsg.FromString,
                    response_serializer=grpc__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab6.Lab6Grpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lab6Grpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6.Lab6Grpc/PerformAdd',
            grpc__pb2.addMsg.SerializeToString,
            grpc__pb2.addReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImageDimensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6.Lab6Grpc/ImageDimensions',
            grpc__pb2.rawImageMsg.SerializeToString,
            grpc__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformDotProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6.Lab6Grpc/PerformDotProduct',
            grpc__pb2.dotProductMsg.SerializeToString,
            grpc__pb2.dotProductReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JsonImageDimensions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab6.Lab6Grpc/JsonImageDimensions',
            grpc__pb2.jsonImageMsg.SerializeToString,
            grpc__pb2.imageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
